// <auto-generated />
namespace Mystic_ToDo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class RecreateFoldersTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RecreateFoldersTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202412312222345_RecreateFoldersTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
