// <auto-generated />
namespace Mystic_ToDo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class IntialCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntialCreate));
        
        string IMigrationMetadata.Id
        {
<<<<<<<< HEAD:Mystic ToDo/Migrations/202501010024294_IntialCreate.Designer.cs
            get { return "202501010024294_IntialCreate"; }
========
            get { return "202412312208487_InitialCreate"; }
>>>>>>>> 6cb8963b939d9fce60f202474f4ebd27b162efce:Mystic ToDo/Migrations/202412312208487_InitialCreate.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
