//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mystic_ToDo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int Reminder_Id { get; set; }
        public string Reminder_Name { get; set; }
        public string Reminder_Description { get; set; }
        public Nullable<bool> Reminder_IsComplete { get; set; }
        public Nullable<bool> Reminder_HasAlarm { get; set; }
        public Nullable<System.DateTime> Reminder_Date { get; set; }
        public Nullable<System.DateTime> Reminder_Time { get; set; }
        public Nullable<bool> Reminder_IsPeriodic { get; set; }
        public Nullable<bool> Reminder_PeriodicActive { get; set; }
        public Nullable<int> Reminder_PeriodicIntervalLabel { get; set; }
        public Nullable<System.DateTime> Reminder_NextPeriodicDate { get; set; }
        public Nullable<System.DateTime> Reminder_NextPeriodicTime { get; set; }
    
        public virtual Timeframe Timeframe { get; set; }
    }
}
